#
# Use AdoptOpenJDK 14 image.
#
FROM adoptopenjdk:14-jdk-hotspot

#
# Install Piranha Server
#
ADD target/piranha-server.tar.gz /usr/local/

#
# Setup WORKDIR.
#
WORKDIR /usr/local/piranha/bin

#
# Setup CMD.
#
CMD ["sh", "run.sh"]
