name: build-docs
on: 
  push:
    paths:
      - 'docs/**'
      - 'maven/**'
    branches:
      - 'current'
    tags-ignore:
      - 'v*'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Piranha
      uses: actions/checkout@v4
    - name: Checkout Piranha Website
      uses: actions/checkout@v4
      with:
        repository: piranhacloud/piranha-website
        token: ${{ secrets.GIT_PASSWORD }}
        path: piranha-website
        ref: 'gh-pages'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: |
        cd docs
        mvn -B -DskipTests -DskipITs -ntp site
        cd ../
        rm -rf piranha-website/snapshot || true
        mkdir -p piranha-website/snapshot || true
        cp -R docs/target/site/* piranha-website/snapshot/
        cd piranha-website
        git config --global user.email "noreply@piranha.cloud"
        git config --global user.name "Automated publish"
        git add .
        git commit -a -m "Publishing documentation" || true
        git push
  maven-plugin:
    needs: docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Piranha
      uses: actions/checkout@v4
    - name: Checkout Piranha Website
      uses: actions/checkout@v4
      with:
        repository: piranhacloud/piranha-website
        token: ${{ secrets.GIT_PASSWORD }}
        path: piranha-website
        ref: 'gh-pages'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: |
        mvn -B -DskipTests -DskipITs -ntp install
        cd maven/plugin
        mvn -B -DskipTests -DskipITs -ntp site
        cd ../..
        rm -rf piranha-website/snapshot/maven-plugin || true
        mkdir -p piranha-website/snapshot/maven-plugin || true
        cp -R maven/plugin/target/site/* piranha-website/snapshot/maven-plugin/
        cd piranha-website
        git config --global user.email "noreply@piranha.cloud"
        git config --global user.name "Automated publish"
        git add .
        git commit -a -m "Publishing Maven plugin documentation" || true
        git push
        