name: dockerhub
on: 
  push:
    branches:
      - 'current'
    tags-ignore:
      - 'v*'
jobs:
  dockerhub:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Maven
      run: mvn -B -DskipTests=true -DskipITs=true -ntp -P '!test' verify
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Piranha Server Docker image
      run: |
        cd server/standard
        docker build -f Dockerfile.amd64 -t piranhacloud/server:amd64-latest .
        docker build --platform linux/arm64/v8 -f Dockerfile.arm64v8 -t piranhacloud/server:arm64v8-latest .
        docker push piranhacloud/server:amd64-latest
        docker push piranhacloud/server:arm64v8-latest
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create --amend piranhacloud/server:latest \
          piranhacloud/server:amd64-latest \
          piranhacloud/server:arm64v8-latest
        docker manifest annotate piranhacloud/server:latest \
          piranhacloud/server:amd64-latest --os linux --arch amd64
        docker manifest annotate piranhacloud/server:latest \
          piranhacloud/server:arm64v8-latest --os linux --arch arm64 --variant v8
        docker manifest push piranhacloud/server:latest
    - name: Build Piranha Micro Docker image
      run: |
        cd micro/standard
        docker build -f Dockerfile.amd64 -t piranhacloud/micro:amd64-latest .
        docker build --platform linux/arm64/v8 -f Dockerfile.arm64v8 -t piranhacloud/micro:arm64v8-latest .
        docker push piranhacloud/micro:amd64-latest
        docker push piranhacloud/micro:arm64v8-latest
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create piranhacloud/micro:latest \
          piranhacloud/micro:amd64-latest \
          piranhacloud/micro:arm64v8-latest
        docker manifest annotate piranhacloud/micro:latest \
          piranhacloud/micro:amd64-latest --os linux --arch amd64
        docker manifest annotate piranhacloud/micro:latest \
          piranhacloud/micro:arm64v8-latest --os linux --arch arm64 --variant v8
        docker manifest push piranhacloud/micro:latest
