name: experimental
on: 
  push:
    branches:
      - 'current'
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        distribution: ['temurin', 'oracle']
        java: [ '23', '24-ea', '25-ea' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B -ntp -T 1 install
