name: ext-quicklook
on: 
  push:
    tags-ignore:
      - 'v*'
jobs:
  quicklook:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -ntp -P '!test' install
    - name: Run Quicklook tests
      run: |
        cd external/quicklook
        mvn -ntp install
