name: stale
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Analyze with SonarCloud
      run: |
        mvn -B -ntp install verify site \
        sonar:sonar -Dsonar.projectKey=piranhacloud_piranha \
        -Dsonar.organization=piranhacloud -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_LOGIN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
