name: tck-coreprofile
on: 
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  annotations:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/tck/annotations
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/tck/annotations/runner/target/failsafe-reports/*IT.xml"
      if: always()
  atinject:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/atinject
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/coreprofile-tck/atinject/target/tck/example/target/surefire-reports/TEST-*.xml"
      if: always()
  cdi:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/cdi
        mvn -B -ntp -T 1 verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/coreprofile-tck/cdi/runner/target/surefire-reports/junitreports/TEST-*.xml"
      if: always()
  coreprofile:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/coreprofile
        mvn -B -ntp verify        
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/coreprofile-tck/coreprofile/runner/target/failsafe-reports/**/TEST-*.xml"
      if: always()
  jsonb:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/jsonb
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/coreprofile-tck/jsonb/target/tck/bin/target/surefire-reports/TEST-*.xml"
      if: always()
  jsonp:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/jsonp
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          external/coreprofile-tck/jsonp/target/tck/bin/tck-tests/target/surefire-reports/TEST-*.xml
          external/coreprofile-tck/jsonp/target/tck/bin/tck-tests-pluggability/target/surefire-reports/TEST-*.xml
      if: always()
  rest:
    if: github.repository == 'piranhacloud/piranha'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/coreprofile-tck/rest
        mvn -B -ntp verify        
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/coreprofile-tck/rest/runner/target/failsafe-reports/**/TEST-*.xml"
      if: always()
